name: Docker

on: [push, pull_request]

env:
  IMAGE_NAME: node-dynamic-ip

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test Image Build
        run: docker build . --file ./dockerFiles/Dockerfile --tag $IMAGE_NAME
